name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Updated to latest version

      - name: Ensure dist directory exists
        run: mkdir -p dist  # Ensure directory exists

      - name: Generate Snake
        id: generate-snake
        uses: Platane/snk@v3  # Updated to latest version
        with:
          github_user_name: PasinduOG
          outputs: |
            dist/snake.svg

      - name: Commit and push the generated snake
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist/snake.svg
          git commit -m "Generated snake" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
